"""crear tablas comprobantes y lineas

Revision ID: 5079bdcc3bc9
Revises: 67c4c5033c0e
Create Date: 2026-06-19 19:46:20.957002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5079bdcc3bc9'
down_revision: Union[str, Sequence[str], None] = '67c4c5033c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprobantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('tipo_doc', sa.String(length=40), nullable=False),
    sa.Column('consecutivo', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('periodo', sa.String(length=6), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=True),
    sa.Column('emisor_nombre', sa.String(length=255), nullable=False),
    sa.Column('emisor_cedula', sa.String(length=20), nullable=False),
    sa.Column('receptor_nombre', sa.String(length=255), nullable=False),
    sa.Column('receptor_cedula', sa.String(length=20), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_gravado', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_exento', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_exonerado', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_no_sujeto', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_iva', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('total_comprobante', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('estado_hacienda', sa.String(length=20), nullable=True),
    sa.Column('xml_raw', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comprobantes_clave'), 'comprobantes', ['clave'], unique=True)
    op.create_index(op.f('ix_comprobantes_cliente_id'), 'comprobantes', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_comprobantes_emisor_cedula'), 'comprobantes', ['emisor_cedula'], unique=False)
    op.create_index(op.f('ix_comprobantes_periodo'), 'comprobantes', ['periodo'], unique=False)
    op.create_index(op.f('ix_comprobantes_receptor_cedula'), 'comprobantes', ['receptor_cedula'], unique=False)
    op.create_table('lineas_comprobante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('cabys', sa.String(length=20), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('base_imponible', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('tarifa_codigo', sa.String(length=4), nullable=False),
    sa.Column('tarifa_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('iva_monto', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('clasificacion', sa.String(length=40), nullable=True),
    sa.Column('sub_clasificacion', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineas_comprobante_comprobante_id'), 'lineas_comprobante', ['comprobante_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineas_comprobante_comprobante_id'), table_name='lineas_comprobante')
    op.drop_table('lineas_comprobante')
    op.drop_index(op.f('ix_comprobantes_receptor_cedula'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_periodo'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_emisor_cedula'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_cliente_id'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_clave'), table_name='comprobantes')
    op.drop_table('comprobantes')
    # ### end Alembic commands ###
