"""crear tabla clientes

Revision ID: 67c4c5033c0e
Revises: 8b609e681399
Create Date: 2026-06-19 15:24:26.086911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c4c5033c0e'
down_revision: Union[str, Sequence[str], None] = '8b609e681399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo_cedula', sa.String(length=20), nullable=False),
    sa.Column('regimen', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cedula'), 'clientes', ['cedula'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_cedula'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
