"""crear tabla entradas_manuales

Revision ID: bce9e77abf9e
Revises: c674f6fcd420
Create Date: 2026-06-22 12:13:00.233203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce9e77abf9e'
down_revision: Union[str, Sequence[str], None] = 'c674f6fcd420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entradas_manuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=6), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('monto', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('tarifa', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('no_sujeto', sa.Boolean(), nullable=False),
    sa.Column('deducible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entradas_manuales_cliente_id'), 'entradas_manuales', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_entradas_manuales_periodo'), 'entradas_manuales', ['periodo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entradas_manuales_periodo'), table_name='entradas_manuales')
    op.drop_index(op.f('ix_entradas_manuales_cliente_id'), table_name='entradas_manuales')
    op.drop_table('entradas_manuales')
    # ### end Alembic commands ###
