"""crear tabla reglas_clasificacion

Revision ID: c674f6fcd420
Revises: f476851486d4
Create Date: 2026-06-20 21:37:54.269428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c674f6fcd420'
down_revision: Union[str, Sequence[str], None] = 'f476851486d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas_clasificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=True),
    sa.Column('cabys', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=10), nullable=True),
    sa.Column('clasificacion', sa.String(length=40), nullable=False),
    sa.Column('sub_clasificacion', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglas_clasificacion_cabys'), 'reglas_clasificacion', ['cabys'], unique=False)
    op.create_index(op.f('ix_reglas_clasificacion_cedula'), 'reglas_clasificacion', ['cedula'], unique=False)
    op.create_index(op.f('ix_reglas_clasificacion_cliente_id'), 'reglas_clasificacion', ['cliente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reglas_clasificacion_cliente_id'), table_name='reglas_clasificacion')
    op.drop_index(op.f('ix_reglas_clasificacion_cedula'), table_name='reglas_clasificacion')
    op.drop_index(op.f('ix_reglas_clasificacion_cabys'), table_name='reglas_clasificacion')
    op.drop_table('reglas_clasificacion')
    # ### end Alembic commands ###
