"""lineas: tarifa_label y tipo; FK cliente_id SET NULL

Revision ID: f476851486d4
Revises: 5079bdcc3bc9
Create Date: 2026-06-20 08:12:10.285591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f476851486d4'
down_revision: Union[str, Sequence[str], None] = '5079bdcc3bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comprobantes_cliente_id_fkey'), 'comprobantes', type_='foreignkey')
    op.create_foreign_key(None, 'comprobantes', 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')
    op.add_column('lineas_comprobante', sa.Column('tarifa_label', sa.String(length=20), nullable=False, server_default=''))
    op.add_column('lineas_comprobante', sa.Column('tipo', sa.String(length=10), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lineas_comprobante', 'tipo')
    op.drop_column('lineas_comprobante', 'tarifa_label')
    op.drop_constraint(None, 'comprobantes', type_='foreignkey')
    op.create_foreign_key(op.f('comprobantes_cliente_id_fkey'), 'comprobantes', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###
